name: assisten_tour_flutter
description: "Assistant Tour - Demo BI"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2  # <-- UDAH UPDATE VERSI WEB SUPPORT
  provider: ^6.1.2      # <-- TAMBAH INI BUAT STATE

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bali.jpg
    - assets/images/bromo.jpg
    - assets/images/labuan_bajo.jpg
    - assets/images/raja_ampat.png
    - assets/images/danau_toba.png
    - assets/images/borobudur.png
    - assets/images/nusa_penida.png
    - assets/images/tana_toraja.png
    - assets/banners/banner1.jpg
    - assets/banners/banner2.jpg
    - assets/banners/banner3.jpg
