name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bali.jpg
    - assets/images/bromo.jpg
    - assets/images/labuan_bajo.jpg
    - assets/images/raja_ampat.png
    - assets/images/danau_toba.png
    - assets/images/borobudur.png
    - assets/images/nusa_penida.png
    - assets/images/tana_toraja.png
    - assets/banners/banner1.jpg
    - assets/banners/banner2.jpg
    - assets/banners/banner3.jpg
